# Generated by Django 4.2.11 on 2025-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_premium_preview',
            field=models.BooleanField(default=False, help_text='If True, this note is premium preview only and cannot be downloaded.'),
        ),
    ]
